import { PolicyChoices } from "../../types";

export const nationalityItems: PolicyChoices[] = [
  { value: "A", label: "A", tag: true },
  { value: "AFG", label: "Afghanistan" },
  { value: "ALB", label: "Albania" },
  { value: "DZA", label: "Algeria" },
  { value: "AND", label: "Andorra" },
  { value: "AGO", label: "Angola" },
  { value: "ATG", label: "Antigua and Barbuda" },
  { value: "ARG", label: "Argentina" },
  { value: "ARM", label: "Armenia" },
  { value: "AUS", label: "Australia" },
  { value: "AUT", label: "Austria" },
  { value: "AZE", label: "Azerbaijan" },
  { value: "B", label: "B", tag: true },
  { value: "BHS", label: "Bahamas" },
  { value: "BHR", label: "Bahrain" },
  { value: "BGD", label: "Bangladesh" },
  { value: "BRB", label: "Barbados" },
  { value: "BLR", label: "Belarus" },
  { value: "BEL", label: "Belgium" },
  { value: "BLZ", label: "Belize" },
  { value: "BEN", label: "Benin" },
  { value: "BTN", label: "Bhutan" },
  { value: "BOL", label: "Bolivia" },
  { value: "BIH", label: "Bosnia and Herzegovina" },
  { value: "BWA", label: "Botswana" },
  { value: "BRA", label: "Brazil" },
  { value: "BRN", label: "Brunei Darussalam" },
  { value: "BGR", label: "Bulgaria" },
  { value: "BFA", label: "Burkina Faso" },
  { value: "BDI", label: "Burundi" },
  { value: "C", label: "C", tag: true },
  { value: "CPV", label: "Cabo Verde" },
  { value: "KHM", label: "Cambodia" },
  { value: "CMR", label: "Cameroon" },
  { value: "CAN", label: "Canada" },
  { value: "CAF", label: "Central African Republic" },
  { value: "TCD", label: "Chad" },
  { value: "CHL", label: "Chile" },
  { value: "CHN", label: "China" },
  { value: "COL", label: "Colombia" },
  { value: "COM", label: "Comoros" },
  { value: "COG", label: "Congo" },
  { value: "CRI", label: "Costa Rica" },
  { value: "CIV", label: "Cote Divoire" },
  { value: "HRV", label: "Croatia" },
  { value: "CUB", label: "Cuba" },
  { value: "CYP", label: "Cyprus" },
  { value: "CZE", label: "Czech Republic" },
  { value: "D", label: "D", tag: true },
  { value: "PRK", label: "Democratic Peoples Republic of Korea" },
  { value: "COD", label: "Democratic Republic of the Congo" },
  { value: "DNK", label: "Denmark" },
  { value: "DJI", label: "Djibouti" },
  { value: "DMA", label: "Dominica" },
  { value: "DOM", label: "Dominican Republic" },
  { value: "E", label: "E", tag: true },
  { value: "ECU", label: "Ecuador" },
  { value: "EGY", label: "Egypt" },
  { value: "SLV", label: "El Salvador" },
  { value: "GNQ", label: "Equatorial Guinea" },
  { value: "ERI", label: "Eritrea" },
  { value: "EST", label: "Estonia" },
  { value: "SWZ", label: "Eswatini" },
  { value: "ETH", label: "Ethiopia" },
  { value: "F", label: "F", tag: true },
  { value: "FSM", label: "Federated States of Micronesia" },
  { value: "FJI", label: "Fiji" },
  { value: "FIN", label: "Finland" },
  { value: "FRA", label: "France" },
  { value: "G", label: "G", tag: true },
  { value: "GAB", label: "Gabon" },
  { value: "GMB", label: "Gambia" },
  { value: "GEO", label: "Georgia" },
  { value: "D", label: "Germany" },
  { value: "GHA", label: "Ghana" },
  { value: "GRC", label: "Greece" },
  { value: "GRD", label: "Grenada" },
  { value: "GTM", label: "Guatemala" },
  { value: "GIN", label: "Guinea" },
  { value: "GNB", label: "Guinea Bissau" },
  { value: "GUY", label: "Guyana" },
  { value: "H", label: "H", tag: true },
  { value: "HTI", label: "Haiti" },
  { value: "HND", label: "Honduras" },
  { value: "CHN", label: "Hong Kong Sar" },
  { value: "HUN", label: "Hungary" },
  { value: "I", label: "I", tag: true },
  { value: "ISL", label: "Iceland" },
  { value: "IND", label: "India" },
  { value: "IDN", label: "Indonesia" },
  { value: "IRN", label: "Iran (Islamic Republic of)" },
  { value: "IRQ", label: "Iraq" },
  { value: "IRL", label: "Ireland" },
  { value: "ISR", label: "Israel" },
  { value: "ITA", label: "Italy" },
  { value: "J", label: "J", tag: true },
  { value: "JAM", label: "Jamaica" },
  { value: "JPN", label: "Japan" },
  { value: "JOR", label: "Jordan" },
  { value: "K", label: "K", tag: true },
  { value: "KAZ", label: "Kazakhstan" },
  { value: "KEN", label: "Kenya" },
  { value: "KIR", label: "Kiribati" },
  { value: "RKS", label: "Kosovo" },
  { value: "KWT", label: "Kuwait" },
  { value: "KGZ", label: "Kyrgyzstan" },
  { value: "L", label: "L", tag: true },
  { value: "LAO", label: "Lao Peoples Democratic Republic" },
  { value: "LVA", label: "Latvia" },
  { value: "LBN", label: "Lebanon" },
  { value: "LSO", label: "Lesotho" },
  { value: "LBR", label: "Liberia" },
  { value: "LBY", label: "Libyan Arab Jamahiriya" },
  { value: "LIE", label: "Liechtenstein" },
  { value: "LTU", label: "Lithuania" },
  { value: "LUX", label: "Luxembourg" },
  { value: "M", label: "M", tag: true },
  { value: "CHN", label: "Macao Sar" },
  { value: "MDG", label: "Madagascar" },
  { value: "MWI", label: "Malawi" },
  { value: "MYS", label: "Malaysia" },
  { value: "MDV", label: "Maldives" },
  { value: "MLI", label: "Mali" },
  { value: "MLT", label: "Malta" },
  { value: "MHL", label: "Marshall Islands" },
  { value: "MRT", label: "Mauritania" },
  { value: "MUS", label: "Mauritius" },
  { value: "MEX", label: "Mexico" },
  { value: "MDA", label: "Moldova" },
  { value: "MCO", label: "Monaco" },
  { value: "MNG", label: "Mongolia" },
  { value: "MNE", label: "Montenegro" },
  { value: "MAR", label: "Morocco" },
  { value: "MOZ", label: "Mozambique" },
  { value: "MMR", label: "Myanmar" },
  { value: "N", label: "N", tag: true },
  { value: "NAM", label: "Namibia" },
  { value: "NRU", label: "Nauru" },
  { value: "NPL", label: "Nepal" },
  { value: "NLD", label: "Netherlands" },
  { value: "NZL", label: "New Zealand" },
  { value: "NIC", label: "Nicaragua" },
  { value: "NER", label: "Niger" },
  { value: "NGA", label: "Nigeria" },
  { value: "MKD", label: "North Macedonia" },
  { value: "NOR", label: "Norway" },
  { value: "O", label: "O", tag: true },
  { value: "OMN", label: "Oman" },
  { value: "P", label: "P", tag: true },
  { value: "PAK", label: "Pakistan" },
  { value: "PLW", label: "Palau" },
  { value: "PSE", label: "Palestinian Territory Occupied" },
  { value: "PAN", label: "Panama" },
  { value: "PNG", label: "Papua New Guinea" },
  { value: "PRY", label: "Paraguay" },
  { value: "PER", label: "Peru" },
  { value: "PHL", label: "Philippines" },
  { value: "POL", label: "Poland" },
  { value: "PRT", label: "Portugal" },
  { value: "Q", label: "Q", tag: true },
  { value: "QAT", label: "Qatar" },
  { value: "R", label: "R", tag: true },
  { value: "XXC", label: "Refugee (other than XXB)" },
  { value: "XXB", label: "Refugee (XXB)" },
  { value: "KOR", label: "Republic of Korea" },
  { value: "ROU", label: "Romania" },
  { value: "RUS", label: "Russian Federation" },
  { value: "RWA", label: "Rwanda" },
  { value: "S", label: "S", tag: true },
  { value: "KNA", label: "Saint Kitts and Nevis" },
  { value: "LCA", label: "Saint Lucia" },
  { value: "VCT", label: "Saint Vincent and the Grenadines" },
  { value: "WSM", label: "Samoa" },
  { value: "SMR", label: "San Marino" },
  { value: "STP", label: "Sao Tome and Principe" },
  { value: "SAU", label: "Saudi Arabia" },
  { value: "SEN", label: "Senegal" },
  { value: "SRB", label: "Serbia" },
  { value: "SYC", label: "Seychelles" },
  { value: "SLE", label: "Sierra Leone" },
  { value: "SVK", label: "Slovakia" },
  { value: "SVN", label: "Slovenia" },
  { value: "SLB", label: "Solomon Islands" },
  { value: "SOM", label: "Somalia" },
  { value: "ZAF", label: "South Africa" },
  { value: "ESP", label: "Spain" },
  { value: "LKA", label: "Sri Lanka" },
  { value: "XXA", label: "Stateless" },
  { value: "SDN", label: "Sudan" },
  { value: "SUR", label: "Suriname" },
  { value: "SWE", label: "Sweden" },
  { value: "CHE", label: "Switzerland" },
  { value: "SYR", label: "Syrian Arab Republic" },
  { value: "T", label: "T", tag: true },
  { value: "TWN", label: "Taiwan" },
  { value: "TJK", label: "Tajikistan" },
  { value: "TZA", label: "Tanzania" },
  { value: "THA", label: "Thailand" },
  { value: "TLS", label: "Timor Leste" },
  { value: "TGO", label: "Togo" },
  { value: "TON", label: "Tonga" },
  { value: "TTO", label: "Trinidad and Tobago" },
  { value: "TUN", label: "Tunisia" },
  { value: "TUR", label: "Turkey" },
  { value: "TKM", label: "Turkmenistan" },
  { value: "TUV", label: "Tuvalu" },
  { value: "U", label: "U", tag: true },
  { value: "UGA", label: "Uganda" },
  { value: "UKR", label: "Ukraine" },
  { value: "ARE", label: "United Arab Emirates" },
  { value: "GBR", label: "United Kingdom British Citizen" },
  { value: "GBD", label: "United Kingdom British Dependent Territories Citiz" },
  { value: "GBN", label: "United Kingdom British National (Overseas)" },
  { value: "GBO", label: "United Kingdom British Overseas Citizen" },
  { value: "GBP", label: "United Kingdom British Protected Person" },
  { value: "GBS", label: "United Kingdom British Subject" },
  { value: "UNA", label: "United Nations Agency" },
  { value: "UNO", label: "United Nations Organization" },
  { value: "USA", label: "United States" },
  { value: "XXX", label: "Unknown" },
  { value: "URY", label: "Uruguay" },
  { value: "UZB", label: "Uzbekistan" },
  { value: "V", label: "V", tag: true },
  { value: "VUT", label: "Vanuatu" },
  { value: "VAT", label: "Vatican City State" },
  { value: "VEN", label: "Venezuela" },
  { value: "VNM", label: "Vietnam" },
  { value: "Y", label: "Y", tag: true },
  { value: "YEM", label: "Yemen" },
  { value: "Z", label: "Z", tag: true },
  { value: "ZMB", label: "Zambia" },
  { value: "ZIM", label: "Zimbabwe" },
];
