name: Increment Build Number

on:
  pull_request_review:
    types: [submitted]

jobs:
  increment:
    name: Increment Build Number
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-	
            ${{ runner.os }}-build-	
            ${{ runner.os }}-
      - name: Install Packages
        run: npm install
      - name: Edit Build Number
        run: npm run hooks:pre-merge-commit
      - name: Retreive Build Number
        id: appBuildVersion
        run: |
          OUTPUT=$(jq -r .appBuildVersion package.json)
          echo "::set-output name=appBuildVersion::$OUTPUT"
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: increment AppBuildVersion to ${{ steps.appBuildVersion.outputs.appBuildVersion }}"
          branch: ${{ github.event.pull_request.head.ref }}
