name: scheduled stale action

# Controls when the action will run.
on:
  schedule:
    - cron: '30 1 * * *' # Every day at UTC 1:30 (SGT 9:30)
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  stale:
    uses: rationally-app/ops-aws/.github/workflows/scheduled_stale.yml@master
