name: Test Different Development Environments

on: [pull_request]

# Ensure only a single job or workflow using the same concurrency group will run at a time
# When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending.
concurrency:
  group: ${{ github.ref }}-test-development-environment # The branch or tag ref that triggered the workflow run.

jobs:
  test:
    name: Lint & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        node: [12, 13, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-	
            ${{ runner.os }}-build-	
            ${{ runner.os }}-
      - name: Setup NPM Token
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_TOKEN_SUPPLYALLY_BOT }}
      - name: Install Packages
        run: npm ci
      - name: Typecheck
        run: npx --no-install tsc --noEmit
      - name: Check Lint
        run: npm run lint
      - name: Set Timezone to +8 (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo timedatectl set-timezone Asia/Singapore
      - name: Set Timezone to +8 (MacOS)
        if: startsWith(matrix.os, 'macOS')
        run: sudo systemsetup -settimezone Asia/Singapore
      - name: Set Timezone to +8 (Windows)
        if: startsWith(matrix.os, 'windows')
        run: tzutil /s "Singapore Standard Time"
      - name: Test
        run: npm run test -- --coverage
