name: Test Different Development Environments

on: [pull_request]

# Ensure only a single job or workflow using the same concurrency group will run at a time
# When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress,
# the queued job or workflow will be pending.
concurrency:
  group: ${{ github.ref }} # The branch or tag ref that triggered the workflow run.

jobs:
  test:
    name: Lint & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        node: [12, 13, 14]
    steps:
      - uses: actions/checkout@v2
